/**
 * decrypt.js — Decrypt Text/Data
 * Aliases: .decrypt, .dec
 * 
 * Decrypts the Base64 string generated by .encrypt
 */

const crypto = require('crypto');

async function execute(sock, msg, botData, args) {
    const chatId = msg.key.remoteJid;
    const stringToDecrypt = args.join(' ').trim();

    if (!stringToDecrypt) {
        await sock.sendMessage(chatId, {
            text: '⚠️ Please provide the encrypted string to decrypt.\n\n*Usage:*\n`.decrypt <encrypted_string>`'
        }, { quoted: msg });
        return;
    }

    try {
        // 1. Generate the exact same secret key using the session ID
        const sessionId = botData?.sessionId || 'default_oxbot';
        const secretKey = crypto.createHash('sha256').update(sessionId + '_oxbot_encryption_key').digest('hex');

        // 2. Convert Base64 string back to Buffer
        const combinedBuffer = Buffer.from(stringToDecrypt, 'base64');

        // 3. Extract the IV (first 16 bytes) and the Encrypted Data (the rest)
        const iv = combinedBuffer.subarray(0, 16);
        const encryptedData = combinedBuffer.subarray(16);

        // 4. Create the Decipher
        const decipher = crypto.createDecipheriv('aes-256-cbc', Buffer.from(secretKey, 'hex'), iv);

        // 5. Decrypt the data
        let decrypted = decipher.update(encryptedData, 'hex', 'utf8');
        decrypted += decipher.final('utf8');

        // 6. Send the response
        await sock.sendMessage(chatId, {
            text: `🔓 *Decryption Successful*\n\n*Decoded Message:*\n${decrypted}`
        }, { quoted: msg });

    } catch (err) {
        console.error('[Decrypt Error]:', err.message);
        await sock.sendMessage(chatId, {
            text: '❌ Failed to decrypt. Make sure you copied the whole encrypted string and this is the same bot that encrypted it.'
        }, { quoted: msg });
    }
}

module.exports = {
    name:     'decrypt',
    aliases:  ['dec'],
    desc:     'Decrypt an encrypted string back to text',
    category: 'tools',
    execute,
};